# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Celebrity',
                'verbose_name_plural': 'Celebrities',
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default=('public', 'Public'), max_length=255, verbose_name='Visibility')),
                ('celebrities', models.ManyToManyField(blank=True, null=True, related_name='costumes', to='honey.Celebrity', verbose_name='celebrities')),
            ],
            options={
                'verbose_name': ('Costume',),
                'verbose_name_plural': 'Costumes',
            },
        ),
    ]
