# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_item_celebrities'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='celebrities',
            field=models.ManyToManyField(to='shop.Celebrity'),
        ),
    ]
