# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_celebrities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='celebrities',
            field=models.ManyToManyField(related_name='items', to='shop.Celebrity'),
        ),
    ]
