# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170921_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.TextField(choices=[('public', 'public'), ('authenticated', 'authenticated')], default='public'),
        ),
    ]
