# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170921_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='_quantity',
            new_name='quantity',
        ),
    ]
